### ISSUE TITLE
Fav tab bug

### ISSUE THREAD

**Issue by riseshia** [riseshia/Bonghwa#468]
Faved 탭으로 넘어간 상태에서 새로고침하면 탭은 Faved인 상태에서 탐라만 일반 Now 탭으로 되돌아갑니다. 이때 글을 쓰면 모든 시간대가 --/-- --:--:-- 처럼 처리중으로 보이고, 장작 스택이 쌓여도 알려주지 않습니다(당연히)

**Comment by namgiH** [comment]
일해라 시아링!
